---
title: "score_at_logodds"
author: "Brian Mannakee"
date: "5/14/2018"
output: pdf_document
---
## PRIMARY

```{r primarycutpoints, message=F,warning=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cutpointr)
load("./primary_score_fr.RDA")
#library(patchwork)


# start looking at cutpoints
prior_cut <- cutpointr(primary_score_fr,log_prior_odds,present,metric=F1_score)
mutect_cut <- cutpointr(primary_score_fr,log_mutect_odds,present,metric=F1_score)
summary(prior_cut)
plot(prior_cut)
summary(mutect_cut)
plot(mutect_cut)
```

## RELAPSE

```{r relapsecutpoints, message=F,warning=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cutpointr)
load("./relapse_score_fr.RDA")
#library(patchwork)


# start looking at cutpoints
prior_cut <- cutpointr(relapse_score_fr,log_prior_odds,present,metric=youden)
mutect_cut <- cutpointr(relapse_score_fr,log_mutect_odds,present,metric=youden)
summary(prior_cut)
plot(prior_cut)
summary(mutect_cut)
plot(mutect_cut)
```


- Can we learn anything about how we are doing in the primary from things found in the relapse
- what the hell is going on with the very high odds calls in the false column.